name: build

on:
  - push

env:
  CI: true

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-
      - name: NPM
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: npm run deploy
