name: build

on:
  - push

env:
  CI: true
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package.json') }}
          restore-keys: |
            npm-
      - name: NPM
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |
          touch "${HOME}/.git-credentials"
          touch "${HOME}/.gitconfig"
          echo "https://adamelliotfields:${GH_TOKEN}@github.com" > "${HOME}/.git-credentials"
          cat <<EOF > "${HOME}/.gitconfig"
          [user]
            name = Adam Fields
            email = adam.elliot.fields@gmail.com
          [credential]
            helper = store
          EOF
          npm run deploy
